[package]
name = "ft-main"
version = "0.1.3"
edition = "2021"

[dependencies]
gstd = { git = "https://github.com/gear-tech/gear.git", branch = "stable", features = ["debug"]}
ft-logic-io = { path = "../ft-logic/io" }
ft-main-io = { path = "io" }
primitive-types = { version = "0.12.1", default-features = false }
sp-core-hashing = { version = "5.0.0", default-features = false }
hashbrown = { version = "0.13.1" }

[build-dependencies]
gear-wasm-builder = { git = "https://github.com/gear-tech/gear.git", branch = "stable" }

[dev-dependencies]
gtest = { git = "https://github.com/gear-tech/gear.git", branch = "stable" }
hex-literal = "0.3.4"
sp-core = { version = "6.0.0", git = "https://github.com/gear-tech/substrate.git", branch = "gear-stable" }
light_sr25519 = { git = "https://github.com/gear-tech/gear.git", branch = "stable" }
ft-storage-io = { path = "../ft-storage/io" }
ft-logic-io = { path = "../ft-logic/io" }