[package]
name = "ft-main"
version = "0.1.3"
edition = "2021"

[dependencies]
gstd = { git = "https://github.com/gear-tech/gear.git", features = ["debug"], branch = "stable" }
ft-logic-io = { path = "../ft-logic/io" }
ft-main-io = { path = "io" }
ft-storage-io = { path = "../ft-storage/io" }
primitive-types = { version = "0.12.1", default-features = false }
sp-core-hashing = { version = "6.0.0", default-features = false }
hashbrown = { version = "0.13.1" }
scale-info = { version = "2", default-features = false }
parity-scale-codec = { version = "3", default-features = false }
blake2-rfc = { version = "0.2.18", default-features = false }
gear-core = { git = "https://github.com/gear-tech/gear.git" }

[build-dependencies]
gear-wasm-builder = { git = "https://github.com/gear-tech/gear.git", branch = "stable"}
ft-main-io = { path = "io" }

[dev-dependencies]
gtest = { git = "https://github.com/gear-tech/gear.git", branch = "stable" }
gstd = { git = "https://github.com/gear-tech/gear.git", branch = "stable", features = ["debug"] }
light_sr25519 = { git = "https://github.com/gear-tech/gear.git", branch = "stable" }
hex-literal = "0.3.4"
sp-core = { version = "6.0.0", git = "https://github.com/gear-tech/substrate.git", branch = "gear-stable" }
gclient = { git = "https://github.com/gear-tech/gear.git"}
tokio = "1"
