[package]
name = "oracle-client"
version = "0.1.0"
edition = "2024"

[dependencies]
mockall = { version = "0.12", optional = true }
sails-rs.workspace = true

[build-dependencies]
oracle-app = { path = "../app" }
sails-idl-gen.workspace = true
sails-client-gen.workspace = true

[features]
mocks = ["sails-rs/mockall", "dep:mockall"]
