[package]
name = "nft-io"
version = "0.2.3"
edition = "2021"
license = "MIT"
authors = ["Gear Technologies"]

[dependencies]
gstd = { git = "https://github.com/gear-tech/gear.git", rev = "d4552434" }
gear-lib = { git = "https://github.com/gear-dapps/gear-lib.git", tag = "0.3.1" }
primitive-types = { version = "0.12.1", default-features = false }
