[package]
name = "oracle"
version = "0.1.0"
edition = "2024"

[dependencies]
oracle-app = { path = "app" }

[build-dependencies]
oracle-app = { path = "app" }
sails-rs = { workspace = true, features = ["wasm-builder"] }
sails-idl-gen.workspace = true

[dev-dependencies]
oracle = { path = ".", features = ["wasm-binary"] }
oracle-client = { path = "client" }
sails-rs = { workspace = true, features = ["gtest"] }
tokio = { workspace = true, features = ["rt", "macros"] }

[features]
wasm-binary = []
