[package]
name = "vara-man-app"
version = "0.1.0"
edition = "2024"

[dependencies]
sails-rs.workspace = true
gstd = { workspace = true, features = ["debug"] }
schnorrkel.workspace = true
extended-vft-client.workspace = true
