[package]
name = "rmrk-io"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gstd.workspace = true
scale-info.workspace = true
parity-scale-codec.workspace = true
primitive-types.workspace = true
types.workspace = true
resource-io.workspace = true
gmeta.workspace = true
