[package]
name = "fungible-token"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Gear Technologies"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.1.2", default-features = false, features = ["derive", "full"] }
gstd = { git = "https://github.com/gear-tech/gear.git", features = ["debug"], rev = "6471eb93" }
ft-io = { path = "io" }
primitive-types = { version = "0.11.1", default-features = false, features = ["scale-info"]}
scale-info = { version = "2.2.0", default-features = false, features = ["derive"] }

[dev-dependencies]
gtest = { git = "https://github.com/gear-tech/gear.git", rev = "6471eb93" }

[build-dependencies]
gear-wasm-builder = { git = "https://github.com/gear-tech/gear.git", rev = "6471eb93" }

[patch.'https://github.com/gear-tech/gear.git']
gtest = { git = "https://github.com/gear-dapps/gear.git", rev = "6471eb93" }
gear-wasm-builder = { git = "https://github.com/gear-dapps/gear.git", rev = "6471eb93" }
gcore = { git = "https://github.com/gear-dapps/gear.git", features = ["debug"], rev = "6471eb93" }
gstd = { git = "https://github.com/gear-dapps/gear.git", features = ["debug"], rev = "6471eb93" }