[package]
name = "car-strategy-2"
version = "0.1.0"
edition = "2024"

[dependencies]
car-strategy-app-2 = { path = "app" }

[build-dependencies]
car-strategy-app-2 = { path = "app" }
sails-rs.workspace = true
sails-idl-gen.workspace = true
gear-wasm-builder.workspace = true

[dev-dependencies]
car-strategy-2 = { path = ".", features = ["wasm-binary"] }
sails-rs.workspace = true
tokio.workspace = true

[features]
wasm-binary = []
