[package]
name = "escrow-io"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
authors = ["Gear Technologies"]

[dependencies]
gstd = { git = "https://github.com/gear-tech/gear.git", features = ["debug"] }
codec = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
primitive-types = { version = "0.11", default-features = false, features = ["scale-info"] }
scale-info = { version = "2", default-features = false, features = ["derive"] }
