[package]
name = "rmrk-resource"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
gstd.workspace = true
rmrk-resource-io.workspace = true
rmrk-catalog-io.workspace = true
hashbrown.workspace = true
rmrk-types.workspace = true

[build-dependencies]
gear-wasm-builder.workspace = true
rmrk-resource-io.workspace = true
