[package]
name = "player"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gstd.workspace = true
syndote-io.workspace = true

[build-dependencies]
gear-wasm-builder.workspace = true
player-io.workspace = true
