[package]
name = "tic-tac-toe-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
gstd = { workspace = true, features = ["debug"] }
sails-rs.workspace = true

[dev-dependencies]
gtest.workspace = true
gear-core.workspace = true
gclient.workspace = true
tic-tac-toe-wasm = { path = "../wasm" }
tokio = "1"
