[package]
name = "nft"
version = "0.1.0"
authors = ["Gear Technologies"]
edition = "2021"

[dependencies]
gstd = {git = "https://github.com/gear-tech/gear.git", features = ["debug"] }
primitive-types = { version = "0.11.1", default-features = false, features = ["scale-info"]}
codec = { package = "parity-scale-codec", version = "3.1.2", default-features = false, features = ["derive"] }
scale-info = { version = "2.0.1", default-features = false, features = ["derive"] }
non-fungible-token = {path = "../../non-fungible-token"}
nft-io = {path = "io"}
market-io = {path = "../marketplace/io"}
ft-io = { git = "https://github.com/gear-academy/fungible-token.git" }
royalties = {path = "royalties"}

[dev-dependencies]
gtest = { git = "https://github.com/gear-tech/gear.git"}

[build-dependencies]
gear-wasm-builder = { git = "https://github.com/gear-tech/gear.git" }
