[package]
name = "auto-changed-nft-io"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gstd.workspace = true
gear-lib.workspace = true
primitive-types.workspace = true
scale-info.workspace = true
parity-scale-codec.workspace = true
gmeta.workspace = true
