[package]
name = "supply-chain-io"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
authors = ["Gear Technologies"]

[dependencies]
gstd = { git = "https://github.com/gear-tech/gear.git" }
codec = { package = "parity-scale-codec", version = "3", default-features = false }
primitive-types = { version = "0.11", default-features = false }
scale-info = { version = "2", default-features = false }
