[package]
name = "router-io"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gmeta.workspace = true
gstd.workspace = true
scale-info.workspace = true
parity-scale-codec.workspace = true
