[package]
name = "poker-app"
version = "0.1.0"
edition = "2024"

[dependencies]
sails-rs.workspace = true
gstd.workspace = true
hex-literal.workspace = true
ark-ed-on-bls12-381-bandersnatch = { workspace = true, default-features = false }
ark-ff = { workspace = true, default-features = false }
ark-ec = { workspace = true, default-features = false }
pts-client = { path = "../../pts/client"}
session-service.workspace = true
zk-verification-client = { path = "../../zk-verification/client"}
blake2 = { version = "0.10.6",  default-features = false }

[dev-dependencies]
serde_json.workspace = true
serde.workspace = true
num-bigint.workspace = true
rand.workspace = true
ark-std.workspace = true

[lib]
name = "poker_app"
path = "src/lib.rs"
