[package]
name = "supply-chain"
version = "0.2.0"
edition = "2021"
license = "MIT"
authors = ["Gear Technologies"]

[dependencies]
supply-chain-io = { path = "io" }
gstd = { git = "https://github.com/gear-tech/gear.git", branch = "testnet" }
nft-io = { git = "https://github.com/gear-dapps/non-fungible-token.git", tag = "0.2.9" }
ft-main-io = { git = "https://github.com/gear-dapps/sharded-fungible-token.git", tag = "0.1.4" }
ft-logic-io = { git = "https://github.com/gear-dapps/sharded-fungible-token.git", tag = "0.1.4" }
gear-lib = { git = "https://github.com/gear-dapps/gear-lib.git", tag = "0.3.5" }
hashbrown = "0.13"

[dev-dependencies]
# TODO: unpin after closing https://github.com/gear-tech/gear/issues/2392.
gtest = { git = "https://github.com/gear-tech/gear.git", branch = "testnet" }
gstd = { git = "https://github.com/gear-tech/gear.git", branch = "testnet", features = ["debug"] }
gclient = { git = "https://github.com/gear-tech/gear.git" }
tokio = "1"
pretty_assertions = "1"
supply-chain-state = { path = "state" }
deploy = { path = "deploy" }

[build-dependencies]
gear-wasm-builder = { git = "https://github.com/gear-tech/gear.git", branch = "testnet" }
supply-chain-io = { path = "io" }

[features]
default = ["binary-vendor"]
binary-vendor = []

[workspace]
members = ["state", "deploy"]
