[package]
name = "vara-man"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vara-man-app = { path = "../app" }
sails-rs.workspace = true

[build-dependencies]
gear-wasm-builder.workspace = true
sails-idl-gen.workspace = true
sails-client-gen.workspace = true
vara-man-app = { path = "../app" }
