[package]
name = "multitoken-io"
version = "0.3.1"
edition = "2021"
license = "MIT"
authors = ["Gear Technologies"]

[dependencies]
gstd = { git = "https://github.com/gear-tech/gear.git" }
gear-lib = { git = "https://github.com/gear-dapps/gear-lib.git", tag = "0.3.0"  }
