[package]
name = "dao-state"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Gear Technologies"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gstd = { git = "https://github.com/gear-tech/gear", branch = "stable" }
gmeta = { git = "https://github.com/gear-tech/gear", branch = "stable", features = ["codegen"] }
dao-io = { path = "../io" }

[build-dependencies]
gear-wasm-builder = { git = "https://github.com/gear-tech/gear", branch = "stable", features = ["metawasm"] }