[package]
name = "mt-main"
version = "0.1.2"
edition = "2021"
license = "MIT"
authors = ["Gear Technologies"]

[dependencies]
gstd = { git = "https://github.com/gear-tech/gear.git", rev = "5c685d0f15c412ab6ee019ceaf7ce084426dfb68" }
mt-logic-io = { path = "../mt-logic/io" }
mt-main-io = { path = "io" }
primitive-types = { version = "0.12.1", default-features = false }
sp-core-hashing = { version = "8.0.0", default-features = false }
hashbrown = { version = "0.13.2" }

[build-dependencies]
mt-main-io = { path = "io" }
gear-wasm-builder = { git = "https://github.com/gear-tech/gear.git", rev = "5c685d0f15c412ab6ee019ceaf7ce084426dfb68" }

[dev-dependencies]
gstd = { git = "https://github.com/gear-tech/gear.git", rev = "5c685d0f15c412ab6ee019ceaf7ce084426dfb68", features = ["debug"] }
gtest = { git = "https://github.com/gear-tech/gear.git", rev = "5c685d0f15c412ab6ee019ceaf7ce084426dfb68" }
gclient = { git = "https://github.com/gear-tech/gear.git", rev = "5c685d0f15c412ab6ee019ceaf7ce084426dfb68" }
blake2-rfc = { version = "0.2.18", default-features = false }
subxt = { version = "0.27", default-features = false }
tokio = "1"
