[package]
name = "sharded-fungible-token"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
gstd.workspace = true
sharded-fungible-token-io.workspace = true
sharded-fungible-token-logic-io.workspace = true
primitive-types.workspace = true
sp-core-hashing.workspace = true

[dev-dependencies]
gtest.workspace = true
gstd = { workspace = true, features = ["debug"] }
sp-core.workspace = true
hex-literal.workspace = true
gear-lib-old.workspace = true

[build-dependencies]
gear-wasm-builder.workspace = true
sharded-fungible-token-io.workspace = true
