[package]
name = "syndote-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
syndote-app = { path = "../app" }
sails-rs.workspace = true

[build-dependencies]
gear-wasm-builder.workspace = true
sails-idl-gen.workspace = true
sails-client-gen.workspace = true
syndote-app = { path = "../app" }
