[package]
name = "sharded-multi-token-storage"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
gstd.workspace = true
sharded-multi-token-storage-io.workspace = true
primitive-types.workspace = true
hashbrown.workspace = true

[build-dependencies]
sharded-multi-token-storage-io.workspace = true
gear-wasm-builder.workspace = true
