[package]
name = "galactic-express-app"
version = "0.1.0"
edition = "2024"

[dependencies]
sails-rs.workspace = true
gstd = { workspace = true, features = ["debug"] }
num-traits = { version = "0.2", default-features = false }
