[package]
name = "multitoken"
version = "0.3.2"
authors = ["Gear Technologies"]
license = "MIT"
edition = "2021"

[dependencies]
gstd = { git = "https://github.com/gear-tech/gear.git", features = ["debug"], rev = "d4552434" }
gear-lib = { git = "https://github.com/gear-dapps/gear-lib.git", tag = "0.3.1" }
gear-lib-derive = { git = "https://github.com/gear-dapps/gear-lib.git", tag = "0.3.1" }
multitoken-io = { path = "io" }

[dev-dependencies]
gtest = { git = "https://github.com/gear-tech/gear.git", rev = "d4552434" }

[build-dependencies]
gear-wasm-builder = { git = "https://github.com/gear-tech/gear.git", rev = "d4552434" }
