[package]
name = "ft-logic"
version = "0.1.4"
edition = "2021"

[dependencies]
gstd = { git = "https://github.com/gear-tech/gear.git", branch = "testnet" }
ft-logic-io = { path = "io" }
ft-storage-io = { path = "../ft-storage/io" }
primitive-types = { version = "0.12.1", default-features = false, features = ["scale-info"]}
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }
light_sr25519 = { git = "https://github.com/gear-tech/gear.git", branch = "testnet" }
hashbrown = "0.13.1"

[dev-dependencies]
gtest = { git = "https://github.com/gear-tech/gear.git", branch = "testnet" }
tokio = { version = "1.26.0", features = ["full"] }

[build-dependencies]
gear-wasm-builder = { git = "https://github.com/gear-tech/gear.git", branch = "testnet" }
ft-logic-io = { path = "io" }

