[package]
name = "dutch-auction"
version = "0.1.2"
edition = "2021"
license = "MIT"
authors = ["Gear Technologies"]

[dependencies]
gstd = { git = "https://github.com/gear-tech/gear.git", features = ["debug"], branch = "testnet" }
auction-io = { path = "io" }
primitive-types = { version = "0.12.1", default-features = false, features = ["scale-info"] }
nft-io = { git = "https://github.com/gear-dapps/non-fungible-token.git", tag = "0.2.9" }
gear-lib = { git = "https://github.com/gear-dapps/gear-lib.git", tag = "0.3.5" }
gmeta = { git = "https://github.com/gear-tech/gear", branch = "testnet" }

[dev-dependencies]
gtest = { git = "https://github.com/gear-tech/gear.git", branch = "testnet" }
sp-core = { version = "6.0.0", git = "https://github.com/gear-tech/substrate.git", branch = "gear-stable" }
gclient = { git = "https://github.com/gear-tech/gear.git", branch = "testnet" }
tokio = { version = "1.24.2", features = ["full"] }

[build-dependencies]
gear-wasm-builder = { git = "https://github.com/gear-tech/gear.git", branch = "testnet" }
auction-io = { path = "io" }

[workspace]
members = ["state"]

[features]
binary-vendor = []
