[package]
name = "ft-storage-io"
version = "0.1.1"
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.1.2", default-features = false }
gstd = { git = "https://github.com/gear-tech/gear.git", rev = "d4552434" }
scale-info = { version = "2.2.0", default-features = false }
primitive-types = { version = "0.12.0", default-features = false }
