[package]
name = "ft-main-io"
version = "0.1.2"
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.2.1", default-features = false }
gstd = { git = "https://github.com/gear-tech/gear.git", branch = "stable" }
scale-info = { version = "2.3.0", default-features = false }
primitive-types = { version = "0.12.1", default-features = false }
ft-logic-io = { path = "../../ft-logic/io" }
