[package]
name = "gear-lib"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
gstd.workspace = true
indexmap.workspace = true
ahash.workspace = true
primitive-types.workspace = true

[dev-dependencies]
gstd = { workspace = true, features = ["debug"] }
