[package]
name = "car-strategy-app-2"
version = "0.1.0"
edition = "2024"

[dependencies]
sails-rs.workspace = true
gstd.workspace = true
parity-scale-codec.workspace = true
scale-info.workspace = true
