[package]
name = "market-io"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Gear Technologies"]

[dependencies]
gstd = { git = "https://github.com/gear-tech/gear.git", features = ["debug"] }
codec = { package = "parity-scale-codec", version = "3.1.2", default-features = false }
scale-info = { version = "2.2.0", default-features = false }
primitive-types = { version = "0.11.1", default-features = false, features = ["scale-info"] }
nft-io = { git = "https://github.com/gear-dapps/non-fungible-token.git", tag = "0.2.1" }
sp-core-hashing = { version = "4.0.0", default-features = false }

[patch.'https://github.com/gear-tech/gear.git']
gtest = { git = "https://github.com/gear-dapps/gear.git", rev = "6471eb93" }
gear-wasm-builder = { git = "https://github.com/gear-dapps/gear.git", rev = "6471eb93" }
gcore = { git = "https://github.com/gear-dapps/gear.git", features = ["debug"], rev = "6471eb93" }
gstd = { git = "https://github.com/gear-dapps/gear.git", features = ["debug"], rev = "6471eb93" }
