[package]
name = "dao-light"
version = "0.1.1"
edition = "2021"
authors = ["Gear Technologies"]
license = "MIT"

[dependencies]
gstd = { git = "https://github.com/gear-tech/gear.git", branch = "stable" }
dao-light-io = { path = "io" }
ft-io = { git = "https://github.com/gear-dapps/fungible-token.git", tag = "0.1.3" }
hashbrown = "0.13.2"

[dev-dependencies]
gstd = { git = "https://github.com/gear-tech/gear.git", branch = "stable", features = ["debug"] }
gtest = { git = "https://github.com/gear-tech/gear.git", branch = "stable" }

[build-dependencies]
dao-light-io = { path = "io" }
gear-wasm-builder = { git = "https://github.com/gear-tech/gear.git", branch = "stable" }

[features]
# Used for inserting constants with WASM binaries (NOT paths) of the contract in
# the root crate. Usually these constants used in gclient tests instead of
# strings with paths to the binaries in the "target" directory. If you don't
# like this approach or don't use gclient tests, you can freely remove this
# feature from here and from the rest of the code.
binary-vendor = []

# It's necessary to include all metawasm crates in the workspace section,
# otherwise they'll be ignored by Cargo and won't be built.
[workspace]
members = [
    "state"
]