[package]
name = "multisig-wallet-state"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gstd = { workspace = true }
gmeta = { workspace = true, features = ["codegen"] }
multisig-wallet-io.workspace = true

[build-dependencies]
gear-wasm-builder = { workspace = true, features = ["metawasm"] }
