[package]
name = "sharded-multi-token"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
gstd.workspace = true
sharded-multi-token-logic-io.workspace = true
sharded-multi-token-io.workspace = true
primitive-types.workspace = true
sp-core-hashing.workspace = true

[build-dependencies]
sharded-multi-token-io.workspace = true
gear-wasm-builder.workspace = true

[dev-dependencies]
gstd = { workspace = true, features = ["debug"] }
gtest.workspace = true
gclient.workspace = true
blake2-rfc.workspace = true
tokio.workspace = true

# External binaries
sharded-multi-token-logic.workspace = true
sharded-multi-token-storage.workspace = true
