[package]
name = "dynamic-nft-state"
version = "0.1.0"
edition = "2021"

[dependencies]
gstd = { git = "https://github.com/gear-tech/gear", branch = "testnet" }
gmeta = { git = "https://github.com/gear-tech/gear", branch = "testnet", features = ["codegen"] }
dynamic-nft-io = { path = "../io" }
gear-lib = { git = "https://github.com/gear-dapps/gear-lib.git", tag = "0.3.5" }

[build-dependencies]
gear-wasm-builder = { git = "https://github.com/gear-tech/gear", branch = "testnet", features = ["metawasm"] }
