name: Contracts CI & Build

on:
  push:
    branches: [master]
    tags:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: CI
    uses: ./.github/workflows/contracts-check.yml

  build:
    name: Build
    needs: check
    runs-on: self-hosted
    defaults:
      run:
        working-directory: contracts
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          cargo xtask docs
          cargo b

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload the GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: target/doc

      - name: Deploy GitHub Pages
        uses: actions/deploy-pages@v1

      - name: Release the nightly build
        uses: softprops/action-gh-release@v1
        with:
          name: Nightly
          prerelease: true
          files: |
            contracts/target/wasm32-unknown-unknown/debug/*.*.wasm
            contracts/target/wasm32-unknown-unknown/debug/*.meta.txt

      - name: Release
        if: startsWith(github.ref, "refs/tags/")
        uses: softprops/action-gh-release@v1
        with:
          files: |
            contracts/target/wasm32-unknown-unknown/debug/*.*.wasm
            contracts/target/wasm32-unknown-unknown/debug/*.meta.txt
