name: Contracts CI & Build

on:
  push:
    branches: [master]
    tags:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: self-hosted
    defaults:
      run:
        working-directory: contracts
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build & move the `nightly` tag
        run: |
          ls -al ..
          cargo xtask docs
          rm target/doc/.lock
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git tag -f nightly
          git push --tags

      - name: Upload the GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: contracts/target/doc

      - name: Deploy GitHub Pages
        uses: actions/deploy-pages@v2

      - name: Release the nightly build
        uses: softprops/action-gh-release@v1
        with:
          name: Nightly
          files: contracts/target/doc/help.html

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: contracts/target/doc/help.html
