[package]
name = "auction-state"
version = "0.1.2"
edition = "2021"

[dependencies]
gstd = { git = "https://github.com/gear-tech/gear", branch = "testnet" }
gmeta = { git = "https://github.com/gear-tech/gear", branch = "testnet", features = ["codegen"] }
auction-io = { path = "../io" }

[build-dependencies]
gear-wasm-builder = { git = "https://github.com/gear-tech/gear", features = ["metawasm"], branch = "testnet" }
